/*
 * Copyright (C) 2022 Moacir da Roza Flores <moacirrf@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.moacirrf.netbeans.markdown.ui;

import io.github.moacirrf.netbeans.markdown.Icons;
import io.github.moacirrf.netbeans.markdown.MyConfigurations;
import static io.github.moacirrf.netbeans.markdown.MyConfigurations.ViewMode.SPLIT_VERTICAL;
import java.awt.Graphics;
import static javax.swing.JSplitPane.HORIZONTAL_SPLIT;
import static javax.swing.JSplitPane.VERTICAL_SPLIT;
import javax.swing.SwingUtilities;
import org.apache.batik.util.Platform;

public class TopBar extends javax.swing.JPanel {

    private final SplitPanel splitPanel;

    private boolean splitModeOn;

    private MyConfigurations.ViewMode viewMode;

    /**
     * Creates new form TopBar
     */
    public TopBar(SplitPanel splitPanel) {
        this.viewMode = MyConfigurations.getViewMode();
        this.splitPanel = splitPanel;
        initComponents();
        buttonGroupViewBtn.add(showSourceBtn);
        buttonGroupViewBtn.add(splitModeBtn);
        buttonGroupViewBtn.add(showPreviewBtn);
        showSourceBtn.setIcon(Icons.getICON_SOURCE());
        showPreviewBtn.setIcon(Icons.getICON_PREVIEW());

        switch (viewMode) {
            case SPLIT_HORIZONTAL:
                splitPanel.getSplitPanel().setOrientation(HORIZONTAL_SPLIT);
                split();
                break;

            case SPLIT_VERTICAL:
                splitPanel.getSplitPanel().setOrientation(VERTICAL_SPLIT);
                split();
                break;

            case EDITOR:
                onlySource();
                break;

            case PREVIEW:
                onlyPreview();
                break;
        }
        this.configCheckBoxViewMode();
        this.scrollSync.setSelected(MyConfigurations.isScrollSync());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupViewBtn = new javax.swing.ButtonGroup();
        showSourceBtn = new javax.swing.JToggleButton();
        splitModeBtn = new javax.swing.JToggleButton();
        showPreviewBtn = new javax.swing.JToggleButton();
        scrollSync = new javax.swing.JCheckBox();
        viewModeDefault = new javax.swing.JCheckBox();

        showSourceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/moacirrf/netbeans/markdown/icon_source.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(showSourceBtn, org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.showSourceBtn.text")); // NOI18N
        showSourceBtn.setToolTipText(org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.showSourceBtn.toolTipText")); // NOI18N
        showSourceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSourceBtnActionPerformed(evt);
            }
        });

        splitModeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/moacirrf/netbeans/markdown/icon_horizontal_split.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(splitModeBtn, org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.splitModeBtn.text")); // NOI18N
        splitModeBtn.setToolTipText(org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.splitModeBtn.toolTipText")); // NOI18N
        splitModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitModeBtnActionPerformed(evt);
            }
        });

        showPreviewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/moacirrf/netbeans/markdown/icon_preview.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(showPreviewBtn, org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.showPreviewBtn.text")); // NOI18N
        showPreviewBtn.setToolTipText(org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.showPreviewBtn.toolTipText")); // NOI18N
        showPreviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPreviewBtnActionPerformed(evt);
            }
        });

        scrollSync.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(scrollSync, org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.scrollSync.text")); // NOI18N
        scrollSync.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scrollSync.setMargin(new java.awt.Insets(2, 0, 2, 2));
        scrollSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrollSyncActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(viewModeDefault, org.openide.util.NbBundle.getMessage(TopBar.class, "TopBar.viewModeDefault.text")); // NOI18N
        viewModeDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAsDefaultView(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSourceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitModeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPreviewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollSync)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewModeDefault)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scrollSync)
                        .addComponent(viewModeDefault))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(showSourceBtn)
                        .addComponent(splitModeBtn)
                        .addComponent(showPreviewBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showSourceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSourceBtnActionPerformed
        this.onlySource();
        this.viewMode = MyConfigurations.ViewMode.EDITOR;
        this.configCheckBoxViewMode();
    }//GEN-LAST:event_showSourceBtnActionPerformed

    private void splitModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitModeBtnActionPerformed
        this.split();
        SwingUtilities.invokeLater(() -> {
            switch (splitPanel.getSplitPanel().getOrientation()) {
                case VERTICAL_SPLIT:
                    this.viewMode = MyConfigurations.ViewMode.SPLIT_VERTICAL;
                    break;
                default:
                    this.viewMode = MyConfigurations.ViewMode.SPLIT_HORIZONTAL;
            }
            this.configCheckBoxViewMode();
        });
    }//GEN-LAST:event_splitModeBtnActionPerformed

    private void showPreviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPreviewBtnActionPerformed
        this.onlyPreview();
        this.viewMode = MyConfigurations.ViewMode.PREVIEW;
        this.configCheckBoxViewMode();
    }//GEN-LAST:event_showPreviewBtnActionPerformed

    private void scrollSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrollSyncActionPerformed
        MyConfigurations.setScrollSync(scrollSync.isSelected());
    }//GEN-LAST:event_scrollSyncActionPerformed

    private void setAsDefaultView(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAsDefaultView

        if (this.viewModeDefault.isSelected()) {
            MyConfigurations.setDefaultViewMode(viewMode);
            this.configCheckBoxViewMode();
        }

    }//GEN-LAST:event_setAsDefaultView

    private void onlySource() {
        SwingUtilities.invokeLater(() -> {
            splitPanel.getSplitPanel().getLeftComponent().setVisible(true);
            splitPanel.getSplitPanel().getRightComponent().setVisible(false);
            splitModeOn = false;
            this.showSourceBtn.setSelected(true);
            this.scrollSync.setEnabled(splitModeOn);
        });
    }

    private void configCheckBoxViewMode() {
        SwingUtilities.invokeLater(() -> {
            this.viewModeDefault.setSelected(MyConfigurations.getViewMode() == this.viewMode);
            this.viewModeDefault.setEnabled(!this.viewModeDefault.isSelected());
        });
    }

    private void split() {
        SwingUtilities.invokeLater(() -> {
            splitModeBtn.setSelected(true);
            splitPanel.getSplitPanel().getLeftComponent().setVisible(true);
            splitPanel.getSplitPanel().getRightComponent().setVisible(true);
            if (splitModeOn) {
                switch (splitPanel.getSplitPanel().getOrientation()) {
                    case HORIZONTAL_SPLIT:
                        splitPanel.getSplitPanel().setOrientation(VERTICAL_SPLIT);
                        this.splitModeBtn.setIcon(Icons.getICON_VERTICAL_SPLIT());
                        break;
                    default:
                        splitPanel.getSplitPanel().setOrientation(HORIZONTAL_SPLIT);
                        this.splitModeBtn.setIcon(Icons.getICON_HORIZONTAL_SPLIT());
                }
            }
            splitModeOn = true;
            splitPanel.getSplitPanel().setDividerLocation(0.5);
            this.scrollSync.setEnabled(splitModeOn);
        });
    }

    private void onlyPreview() {
        SwingUtilities.invokeLater(() -> {
            splitPanel.getSplitPanel().getLeftComponent().setVisible(false);
            splitPanel.getSplitPanel().getRightComponent().setVisible(true);
            splitModeOn = false;
            this.showPreviewBtn.setSelected(true);
            this.scrollSync.setEnabled(splitModeOn);
        });
    }

    @Override
    protected void paintComponent(Graphics g) {
        this.scrollSync.setSelected(MyConfigurations.isScrollSync());
        super.paintComponent(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupViewBtn;
    private javax.swing.JCheckBox scrollSync;
    private javax.swing.JToggleButton showPreviewBtn;
    private javax.swing.JToggleButton showSourceBtn;
    private javax.swing.JToggleButton splitModeBtn;
    private javax.swing.JCheckBox viewModeDefault;
    // End of variables declaration//GEN-END:variables

}
