## YAML Template.
---
name: Pre Release
on:
    push:
        branches:
            - main
            
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: NBM
        run: mvn -Dkeypass=${{secrets.KEYPASS}} verify
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.NETBEANS_ACTION_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/*.jar
            target/*.nbm

