## YAML Template.
---
name: Pre Release
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn -Dkeypass=${{secrets.KEYPASS}} verify
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            target/*.jar
            target/*.nbm
            target/*.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
