## YAML Template.
---
name: Pre Release
on:
    push:
        branches:
            - main
            
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: NBM
        run: mvn -Dkeypass=${{secrets.KEYPASS}} verify
      - name: "Automatic Releases"
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.NETBEANS_ACTION_TOKEN }}"
          tag: "latest"
          prerelease: true
          artifacts: "target/*.jar,target/*.nbm"
