## YAML Template.
---
name: Pre Release
on:
    push:
        branches:
            - main
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          repo_token: "${{ secrets.NETBEANS_MARKDOWN_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/*.jar
            target/*.nbm
      - name: NBM
        run: mvn verify
