## YAML Template.
---
name: Pre Release
on:
    push:
        branches:
            - main
            
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.NETBEANS_MARKDOWN_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/*.jar
            target/*.nbm

