## YAML Template.
---
name: Pre Release
on:
    push:
        tags:
            - v*
            
jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: NBM
        run: mvn verify
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.NETBEANS_MARKDOWN_TOKEN }}"
          prerelease: false
          files: |
            target/*.jar
            target/*.nbm

